### ISSUE TITLE
user: Current not implemented on linux/amd64" $HOME=/home/ngrok

### ISSUE THREAD

**Issue by mo-mueller** [wernight/docker-ngrok#15]
I'm following this tutorial to publish a local RocketMap to the web with ngrok: [https://rocketmap.readthedocs.io/en/develop/advanced-install/docker.html#advanced-docker-setup](https://rocketmap.readthedocs.io/en/develop/advanced-install/docker.html#advanced-docker-setup)

Here are the 2 commands regarding ngrok: [https://rocketmap.readthedocs.io/en/develop/advanced-install/docker.html#external-access](https://rocketmap.readthedocs.io/en/develop/advanced-install/docker.html#external-access)

The RocketMap is running correctly, but the ngrok container logs this to me:

```t=2017-08-03T18:43:32+0000 lvl=warn msg="failed to get home directory, using $HOME instead" err="user: Current not implemented on linux/amd64" $HOME=/home/ngrok```

docker info:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.06.0-ce
Storage Driver: devicemapper
 Pool Name: docker-202:1-2711675-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.772GB
 Data Space Total: 107.4GB
 Data Space Available: 47.14GB
 Metadata Space Used: 2.834MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.145GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 987.9MiB
Name: mo-mueller
ID: Q67L:CMIH:UOEU:V6J7:5UES:G7WI:6FQZ:SQZT:TSOD:5RI2:XIJQ:WDSY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

How can I fix that?

**Comment by smebberson** [comment]
I get this issue too.

**Comment by wernight** [comment]
Did you change the default user? May be give part of the command you ran and I'll look into it.

**Comment by leslie-qiwa** [comment]
I get this issue. this is what I got 
```
# ngrok http 80
WARN[01-04|20:44:42] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/amd64" $HOME=/root
```

**Comment by wernight** [comment]
What the command line you're running? I think setting HOME should fix it, e.g. `--env HOME=/home/ngrok` or may be `ENV HOME=/home/ngrok` in the Dockerfile.

**Comment by BeeHiveJava** [comment]
Hey @wernight, this issue seems to still be there for me as of today. I have tried various things:
- Setting the home directory manually
- Changing the default user
- Setting permissions

I'm really not sure where the issue is coming from. If you, or anyone else, seemed to have fixed this, please let us know!

**Comment by Caroga** [comment]
Same here, setting HOME via ENV or anything does not resolve this issue. Any ideas?

**Comment by wernight** [comment]
Thanks for sharing the command that fails.

I do see the warning with: `docker run  wernight/ngrok ngrok http 8080`. However it seems to work. I'll look in fixing that warning if possible.

**Comment by wernight** [comment]
I think I fixed the warning. Note also that running in interactive mode seem to also fix the issue (i.e. with `-it`).

**Comment by wernight** [comment]
Note that the default user is `ngrok` and not `root`. Doesn't that default user work for you?

**Comment by jay341-py** [comment]
./ngrok http 8080                               WARN[01-13|17:19:22] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/arm"

I have this type of error
Please solve this.

**Comment by tindurz** [comment]
Need this command

export USER=$(id -un)

**Comment by gonzalom** [comment]
> Note that the [default user is `ngrok`](https://github.com/wernight/docker-ngrok/blob/master/Dockerfile#L17) and not `root`. Doesn't that default user work for you?

Sorry @wernight, I missed your message.

I didn't tried, I can't tell right now, but it would be a matter of test it, or try @tindurz solution: `export USER=$(id -un)`

**Comment by 0xygyn** [comment]
You can try this.
echo $HOME
echo $USER

Then

set $USER = $HOME

Then 

./ngrok http 80

**Comment by vardipoorm** [comment]
> 

Solve my problem thanks
